
CREATE TABLE ALQUILER
(
	id_alquiler          INTEGER NOT NULL,
	fecha_inicial        TIMESTAMP NULL,
	fecha_final          TIMESTAMP NULL,
	id_habitacion        INTEGER NOT NULL,
	id_cliente           INTEGER NOT NULL,
	id_detalle           INTEGER NOT NULL
);

ALTER TABLE ALQUILER
ADD CONSTRAINT XPKALQUILER PRIMARY KEY (id_alquiler);

CREATE TABLE CLIENTE
(
	id_cliente           INTEGER NOT NULL,
	identificacion       VARCHAR(20) NULL,
	nombres              VARCHAR(200) NULL,
	apellidos            VARCHAR(200) NULL,
	telefono             VARCHAR(100) NULL,
	email                VARCHAR(300) NULL
);

ALTER TABLE CLIENTE
ADD CONSTRAINT XPKCLIENTE PRIMARY KEY (id_cliente);

CREATE TABLE CLIENTE_SERVICIO_ESPECIAL
(
	id_cliente           INTEGER NOT NULL,
	id_servicioEspecial  INTEGER NOT NULL
);

ALTER TABLE CLIENTE_SERVICIO_ESPECIAL
ADD CONSTRAINT XPKCLIENTE_SERVICIO_ESPECIAL PRIMARY KEY (id_cliente,id_servicioEspecial);

CREATE TABLE EMPLEADO
(
	id_empleado          INTEGER NOT NULL,
	codigo               VARCHAR(20) NULL,
	nombre               VARCHAR(300) NULL,
	id_servicioEspecial  INTEGER NOT NULL
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT XPKEMPLEADO PRIMARY KEY (id_empleado);

CREATE TABLE FACTURA
(
	id_factura           INTEGER NOT NULL,
	numero               VARCHAR(20) NULL,
	fecha                DATE NULL,
	valor                DECIMAL(12,2) NULL
);

ALTER TABLE FACTURA
ADD CONSTRAINT XPKFACTURA PRIMARY KEY (id_factura);

CREATE TABLE FACTURA_DETALLE
(
	id_detalle           INTEGER NOT NULL,
	cantidad             INTEGER NULL,
	valor_item           DECIMAL(12,2) NULL,
	id_factura           INTEGER NOT NULL
);

ALTER TABLE FACTURA_DETALLE
ADD CONSTRAINT XPKFACTURA_DETALLE PRIMARY KEY (id_detalle);

CREATE TABLE HABITACION
(
	id_habitacion        INTEGER NOT NULL,
	numero               VARCHAR(20) NULL,
	capacidad            INTEGER NULL,
	tarifa               DECIMAL(12,2) NULL,
	id_tipoH             INTEGER NOT NULL
);

ALTER TABLE HABITACION
ADD CONSTRAINT XPKHABITACION PRIMARY KEY (id_habitacion);

CREATE TABLE HABITACION_TIPO
(
	id_tipoH             INTEGER NOT NULL,
	tipo                 VARCHAR(60) NULL,
	descripcion          VARCHAR(500) NULL
);

ALTER TABLE HABITACION_TIPO
ADD CONSTRAINT XPKHABITACION_TIPO PRIMARY KEY (id_tipoH);

CREATE TABLE RESERVA
(
	id_reserva           INTEGER NOT NULL,
	fecha_inicial        TIMESTAMP NULL,
	fecha_final          TIMESTAMP NULL,
	cantidad_habitaciones INTEGER NULL,
	id_cliente           INTEGER NOT NULL,
	id_habitacion        INTEGER NOT NULL
);

ALTER TABLE RESERVA
ADD CONSTRAINT XPKRESERVA PRIMARY KEY (id_reserva,id_cliente,id_habitacion);

CREATE TABLE SERVICIO_ESPECIAL
(
	id_servicioEspecial  INTEGER NOT NULL,
	codigo               VARCHAR(20) NULL,
	servicio             VARCHAR(300) NULL,
	valor                DECIMAL(12,2) NULL,
	id_detalle           INTEGER NOT NULL
);

ALTER TABLE SERVICIO_ESPECIAL
ADD CONSTRAINT XPKSERVICIO_ESPECIAL PRIMARY KEY (id_servicioEspecial);

ALTER TABLE ALQUILER
ADD CONSTRAINT R_9 FOREIGN KEY (id_habitacion) REFERENCES HABITACION (id_habitacion);

ALTER TABLE ALQUILER
ADD CONSTRAINT R_10 FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente);

ALTER TABLE ALQUILER
ADD CONSTRAINT R_11 FOREIGN KEY (id_detalle) REFERENCES FACTURA_DETALLE (id_detalle);

ALTER TABLE CLIENTE_SERVICIO_ESPECIAL
ADD CONSTRAINT R_2 FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente);

ALTER TABLE CLIENTE_SERVICIO_ESPECIAL
ADD CONSTRAINT R_3 FOREIGN KEY (id_servicioEspecial) REFERENCES SERVICIO_ESPECIAL (id_servicioEspecial);

ALTER TABLE EMPLEADO
ADD CONSTRAINT R_4 FOREIGN KEY (id_servicioEspecial) REFERENCES SERVICIO_ESPECIAL (id_servicioEspecial);

ALTER TABLE FACTURA_DETALLE
ADD CONSTRAINT R_6 FOREIGN KEY (id_factura) REFERENCES FACTURA (id_factura);

ALTER TABLE HABITACION
ADD CONSTRAINT R_5 FOREIGN KEY (id_tipoH) REFERENCES HABITACION_TIPO (id_tipoH);

ALTER TABLE RESERVA
ADD CONSTRAINT R_7 FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente);

ALTER TABLE RESERVA
ADD CONSTRAINT R_8 FOREIGN KEY (id_habitacion) REFERENCES HABITACION (id_habitacion);

ALTER TABLE SERVICIO_ESPECIAL
ADD CONSTRAINT R_12 FOREIGN KEY (id_detalle) REFERENCES FACTURA_DETALLE (id_detalle);
